Homework 27
gornda/microservices pull request #6
Opened 2017-12-03 18:46 UTC by gornda

2017-12-07 09:42 UTC, chromko requested changes
Поправить по замечаниям. Остальное ок

2017-12-07 09:42 UTC, chromko commented on prometheus/Dockerfile
> +ADD alert.rules.yml /etc/prometheus/
Лучше файлы конфигураций, конечно, через Volum'ы подгружать или механизм docker swarm configs.
Зашивать их в образ - нехорошо.

2017-12-07 09:42 UTC, chromko commented on docker-compose.infra.yml
> +networks:
Аккуратно работайте с сетями. У вас и в `docker-compose.yml` описывается создание сетей. Если обе конфигурации будут запущены одна за другой или одновременно - возникнут конфликты. У нас мерджатся эти файлы вместе с помощью `docker compose config` - поэтому здесь описания сетей хватит в одном из файлов

2017-12-27 10:07 UTC, gornda commented
@chromko Убрал дублирование конфигурации сетей.

2017-12-27 12:00 UTC, chromko approved these changes
Теперь ок

2017-12-27 12:12 UTC, merged