Kubernetes-1 (Домашнее задание 28)
gornda/microservices pull request #7
Opened 2017-12-03 18:47 UTC by gornda

2017-12-07 09:34 UTC, chromko commented
Что то в этом PR не так) Тут и Compose смешался и The hard way)

2017-12-07 09:57 UTC, chromko requested changes
Поправить PR

2017-12-27 14:56 UTC, gornda commented
@chromko Убрал лишнее из PR

2017-12-28 10:33 UTC, chromko commented
Теперь ок

2017-12-28 10:33 UTC, chromko approved these changes

2017-12-28 10:49 UTC, merged